services:
  poc-app:
    container_name: poc-app
    build:
      context: .
      target: ${NODE_ENV:-development}
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV:-development}
