# Configuração do SonarQube
sonar.projectKey=next-app
sonar.projectName=next-app
sonar.projectVersion=1.0
sonar.host.url=http://localhost:9000
sonar.login=sqp_7f4114a8736acf72157d84299f3764e1a696b48a

# Definir o diretório do código fonte
sonar.sources=src
sonar.inclusions=coverage/**
sonar.exclusions=node_modules/**,yarn.lock

# Análise de testes e cobertura
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json

# Desativar exclusões do Git
sonar.scm.exclusions.disabled=true
