name: Checks

on:
  push:
    branches: [main]

jobs:
  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: run the typecheck
        run: |
          yarn
          yarn type:check

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: run the prettier
        run: |
          yarn
          yarn prettier:check

  eslint:
    name: ESlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: run the eslint
        run: |
          yarn
          yarn lint:check

  status_check_result:
    if: ${{ always() }}
    name: Checks result
    needs: [typecheck, prettier, eslint]
    runs-on: ubuntu-latest
    steps:
      - run: |
          if [[ "${{needs.typecheck.result}}" == "success" && "${{needs.prettier.result}}" == "success" && "${{needs.eslint.result}}" == "success" ]]; then
            echo "All checks passed"
            exit 0
          else
            echo "Some check failed"
            exit 1
          fi
