name: Tests

on:
  push:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: run the tests
        run: |
          yarn
          yarn test

  tests_result:
    if: ${{ always() }}
    name: Tests result
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - run: |
          if [[ "${{needs.tests.result}}" == "success" ]]; then
            echo "All tests passed"
            exit 0
          else
            echo "Some test failed"
            exit 1
          fi
